text4/booktest/urls.py
from django.conf.urls import url
from booktest import views
urlpatterns=[
    url(r'^$',views.index),
    url(r'^(\d+)',views.show,name="show"),
    url(r'^index2',views.index2),
    url(r'^index3',views.index3),
    url(r'^zhuanyi',views.zhuanyi),
]

text4/text4/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('booktest.urls',namespace='booktest')),
]

text4/booktest/models.py
from django.db import models

class mymanager(models.Manager):
    def get_queryset(self):
        return super(mymanager,self).get_queryset().filter(isdelete=False)
    #创建数据简写方法
    def create(self,btitle,date):
        b=Bookinfo()
        b.btitle=btitle
        b.date=date
        b.bread=0
        b.bcommit=0
        b.isDelete=False
        return b

class Bookinfo(models.Model):
    btitle=models.CharField(max_length=30)
    date=models.DateTimeField(db_column="datetime")
    bread=models.IntegerField()
    bcommit=models.IntegerField()
    isDelete=models.BooleanField()
    class Meta():
        db_table='bookinfo2'


class Heroinfo(models.Model):
    hname=models.CharField(max_length=30)
    hgender=models.BooleanField()
    hcontent=models.TextField()
    isDelete=models.BooleanField()
    hero=models.ForeignKey('Bookinfo')

text4/booktest/views.py
from django.shortcuts import render,redirect
from django.http import *
from booktest import models
# Create your views here.
def index(request):
    list_1=models.Bookinfo.objects.all()
    context={'list':list_1}
    return render(request,'booktest/index.html',context)

def show(request,l1):
    context={'list':l1}
    return render(request,'booktest/show.html',context)

def index2(request):
    return render(request,'booktest/user2.html')

def index3(request):
    return render(request,'booktest/user3.html')

def zhuanyi(request):
    res="<h1>dsa</h1>"
    context={"list":res}
    return render(request,'booktest/zhuanyi.html',context)

text4/templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="color:pink">top</h1>    
    {% block center%}
    {%endblock%}
    <h2>the end</h2>
</body>
</html>

text4/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {#这是一个注释#}
    {%comment%}
    zhushi
    {%endcomment%}
    <ul>
        {#url反向解析,动态生成链接#}
        <a href="{%url 'booktest:show' '123'%}">展示</a>
        {%for book in list%}    
        {%if forloop.counter|divisibleby:"2"%}
        <li style="color:red">{{book.btitle}}</li>
        {%else%}
        <li style="color:blue">{{book.btitle}}</li>
        {%endif%}
        {%endfor%}


    </ul>
</body>
</html>

text4/templates/booktest/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{list}}
    
</body>
</html>

text4/templates/booktest/user1.html
{%extends 'booktest/base.html'%}
{%block center%}
    <table border="1">
        <tr>
            <td height="200px" width="150px">用户导航</td>
            <td height="200px" width="350px">{%block center_2%}
                {%endblock center_2%}
            </td>
        </tr>
    </table>
{%endblock center%}

text4/templates/booktest/user2.html
{%extends 'booktest/user1.html'%}
{%block center_2%}
<h1>商品列表</h1>
{%endblock center_2%}

text4/templates/booktest/user3.html
{%extends 'booktest/user1.html'%}
{%block center_2%}
    <h1>用户信息</h1>
{%endblock%d

text4/templates/booktest/zhuanyi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% autoescape off%}    
    {{list}}
    {%endautoescape%}
    {{list | safe}}
</body>
</html>