bbs/bbs/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('login_in.urls',namespace='login_in')),
    url(r'^', include('bbsapp.urls',namespace='bbsapp')),
    #验证码url
    url(r'^captcha/', include('captcha.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'', include('ckeditor_uploader.urls')),
    url(r'^', include('bbsapp.urls',namespace='kind')),
    url(r'^', include('myhome.urls',namespace='myhome')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 没有这一句无法显示上传的图片

bbs/bbsapp/urls.py
from django.conf.urls import url
from bbsapp import views

urlpatterns=[
    url(r'^$',views.index,name='index'),
    # url(r'^comment$',views.comment,name='comment'),
    # 楼钟楼5条展示评论
    url(r'^comment/this_comment$',views.this_comment,name='this_comment'),
    # 楼钟楼提交
    url(r'^comment/submit$',views.comment_submit,name='comment_submit'),
    # 楼钟楼分页
    url(r'^comment/paginator$',views.comment_paginator,name='comment_paginator'),
    # 评论主页
    url(r'^comment/(?P<pk>\d*)$',views.comment.as_view(),name='comment'),
    # 文章图片
    url(r'^kind/upload',views.kind_upload,name='kind_upload'),
    # 文章提交
    url(r'^comment/article_submit/(?P<pk>\d)$',views.article_submit,name='article_submit'),
    # 板块主页,放入板块id作参数
    url(r'^category/index/(?P<pk>\d+)',views.category_index.as_view(),name='category_index'),
    #搜索
    url(r'^mysearch/$',views.mysearch,name='mysearch'),
    # 多图
    # url(r'^webuploader',views.webuploader,name='webuploader'),
#     个人空间
]

bbs/login_in/urls.py
from django.conf.urls import url
from login_in import views
from bbs import settings

urlpatterns=[
    # url(r'^register$',views.register,name='register'),
    url(r'^register$',views.send.as_view(),name='register'),
    url(r'^login$',views.login.as_view(),name='login'),
    url(r'^login/out$',views.login_out,name='out'),
    url(r'^login/newpassword/$',views.newpassword.as_view(),name='newpassword'),
    #验证码自带视图，不需要写视图函数
]

bbs/bbsapp/models.py
from django.db import models
from django.urls import reverse
from bbs import settings
from ckeditor_uploader.fields import RichTextUploadingField

# 帖子表
class Article(models.Model):
    # 标题
    title = models.CharField(max_length=200,unique=False)
    # 所属板块
    category = models.ForeignKey('Category')
    # 作者
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    # 内容
    content = models.TextField(max_length=2000)
    # 日期
    startime = models.DateTimeField(auto_now_add=True, null=True)
    # 优先级
    dengji = models.IntegerField(default=10)
    # 点击量,内置获取点击函数
    click_count=models.PositiveIntegerField(default=0)
    # 由文章对象获得文章的url
    def get_absolute_url(self):
        return  reverse('bbsapp:comment',kwargs={'pk':self.pk})

    # 阅读量函数
    def count(self):
        self.click_count+=1
        # 值更新阅读量
        self.save(update_fields=['click_count'])
    def __str__(self):
        return str(self.pk)
    # 我的评论


class Comment(models.Model):
    # 当前评论的对象
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    # 评论的文章
    article = models.ForeignKey('Article')
    # 评论时间
    startime = models.DateTimeField(auto_now_add=True)
    # 评论内容
    content = models.TextField(max_length=1000)
    # 评论的谁，父id
    father_id = models.CharField(max_length=80, null=True, blank=True)
    # 所属楼层id
    floor_id = models.CharField(max_length=80, null=True, blank=True)


# 被评论
class to_Comment(models.Model):
    # 用户
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='this_user')
    # 评论id
    comment = models.CharField(max_length=20, default='', null=True)
    # 被评论
    to_comment = models.CharField(max_length=20, default='', null=True)
    #时间
    startime=models.DateTimeField(auto_now_add=True,null=True,blank=True)
    #评论谁
    to_user=models.ForeignKey(settings.AUTH_USER_MODEL,related_name='to_user',null=True,)

# 关注
class like(models.Model):
    # 用户
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    # 评论id
    like = models.CharField(max_length=20, default='', null=True, blank=True)
    # 被评论
    to_like = models.CharField(max_length=20, default='', null=True, blank=True)


# 板块
class Category(models.Model):
    # 版快名
    name = models.CharField(max_length=30)
    # 根据板块对象获得板块url
    def get_absolute_url(self):
        return reverse('bbsapp:category_index',kwargs={'pk':self.pk})

    # 由当前板块id对应的url,指向提交函数
    def get_absolute_url2(self):
        return reverse('bbsapp:article_submit',kwargs={'pk':self.pk})


# 收藏
class Collection(models.Model):
    # 收藏状态
    collection = models.BooleanField(default=False)
    # 对应文章
    article = models.ForeignKey('Article', null=True)
    # 对应用户
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    # 时间
    startime = models.DateTimeField(auto_now_add=True, null=True)


class good(models.Model):
    # 点赞状态,
    click_good = models.BooleanField(default=False)
    # 对应文章
    article = models.ForeignKey('Article', null=True)
    # 时间
    startime = models.DateTimeField(auto_now_add=True, null=True)
    # 用户
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
# Create your models here.

bbs/bbsapp/forms.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.forms import forms


class comment_write(forms.Form):

    content = RichTextUploadingField(verbose_name='正文')

bbs/bbsapp/views.py
import time,re,json,os
from django.shortcuts import render, redirect
from django.http import *
from bbsapp import models
from django.views.generic import ListView
from login_in import models as mo
from django.utils import timezone
from django.core.paginator import Paginator
from bbsapp import forms
from bbs import settings
from django.views.decorators.cache import cache_page
# Create your views here.
# 论坛主页

# @cache_page(60*60)
def index(request):
    return render(request, 'bbsapp/index.html')

# 评论页面获取和分页函数(包括文章内容)
class comment(ListView):
    template_name = 'bbsapp/comment.html'
    # get_queryset拿到的数据的名称
    context_object_name = 'result'
    paginate_by = 5
    article_id=None

    # 调用父类get方法获得url传参
    # ListView执行顺序，get,get_queryset,get_context_object
    def get(self, request, pk, **kwargs):
        self.article_id=pk
        login=request.session.get('login')
        # 记录历史记录
        if login:
            mo.history(user=mo.User.objects.get(id=login.get('id')),
                       article_history=models.Article.objects.get(pk=self.article_id).id).save()
        return super().get(request,pk,**kwargs)
    # 分页数据
    def get_queryset(self):
        # 调用更新阅读量函数
        models.Article.objects.get(id=self.article_id).count()
        # 获取评论分页的数据
        return models.Article.objects.get(id=self.article_id).comment_set.filter(floor_id='None')

    # 视图类中context传参使用get_context_data
    def get_context_data(self, **kwargs):
        # 获得context对象
        context = super(comment, self).get_context_data(**kwargs)
        # 分页对象
        paginator = context.get('paginator')
        # 当前也对象
        page = context.get('page_obj')
        # 是否分页
        is_paginated = context.get('is_paginated')

        # 在context中加入文章
        if self.article_id!=None:
            article=models.Article.objects.get(id=self.article_id)
            context.update({'article':article})
        # 判断是否分页
        if is_paginated:
            res = self.mypaginator(paginator, page, is_paginated)
            context.update(res)
            return context
        return context

    def mypaginator(self, paginator, page, is_paginated):
        left, right = [], []
        left_dian, right_dian = False, False
        first, last = False, False
        nowpage_num = page.number
        page_list = paginator.page_range
        all_page_number = paginator.num_pages
        if nowpage_num == 1:
            right = page_list[nowpage_num:nowpage_num + 2]
            if right[-1] < all_page_number - 1:
                right_dian = True
            if right[-1] < all_page_number:
                last = True
        elif nowpage_num == all_page_number:
            left = page_list[nowpage_num - 3:nowpage_num - 1]
            if left[0] > page_list[1]:
                left_dian = True
            if left[0] > page_list[0]:
                first = True
        else:
            left = page_list[nowpage_num - 2:nowpage_num - 1]
            right = page_list[nowpage_num:nowpage_num + 2]
            if right[-1] < all_page_number - 1:
                right_dian = True
            if right[-1] < all_page_number:
                last = True
            if left[0] > page_list[1]:
                left_dian = True
            if left[0] > page_list[0]:
                first = True
        context = {
            'left': left,
            'right': right,
            'left_dian': left_dian,
            'right_dian': right_dian,
            'first': first,
            'last': last
        }
        return context

# 板块分页类，继承评论分页类
class category_index(comment):
    template_name = 'bbsapp/lol_index.html'
    # get_queryset()得到的数据的name
    context_object_name = 'a_list'
    paginate_by = 10
    category_id=None
    # 首页展示部分内容,listview源码是先分页在返回context,所以context只有10条，
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        result=context.get('a_list')
        filter_context=[]
        for i in result:
            filter_context.append(''.join(re.findall('<img src="/media/.{1,60}/>',i.content)[:3]))
        context.update({'only_image':filter_context})
        return context

    # 筛选出文章列表
    def get_queryset(self):
        return  models.Category.objects.filter(pk=self.category_id)[0].article_set.all().order_by('-startime')
    #  获得文章id

    def get(self, request, pk, **kwargs):
        # 从get请求中拿到文章id
        self.category_id=pk
        # get源码中第一步获取get_queryset()，所以先重写get_queryset()拿到筛选数据
        return  super(comment,self).get(request,pk,**kwargs)


#显示多级评论
def this_comment(request):
    #父id
    floor_id=request.POST['floor_id']
    #评论文章id
    article_id=request.POST['article']

    #  获得文章该楼曾所有评论的集合
    res=models.Comment.objects.filter(floor_id=floor_id)[:5]
    count=models.Comment.objects.filter(floor_id=floor_id).count()
    res_1=[]
    for i in res:
        fathername=models.Comment.objects.get(id=i.father_id).user.username
        if i.father_id==i.floor_id:
            fathername=' '+fathername
        res_1.append({'id':i.id,
                    'startime':i.startime,
                    'content':i.content,
                    'fathername':fathername,
                    'username':i.user.username}
                      )
    return JsonResponse({'result':res_1,'floor_id':floor_id,'count':count})



#提交评论
def comment_submit(request):
    #父id,如果为楼层评论,默认为None
    father_id=request.POST.get('father_id',None)
    #一级id,即用户id
    user_id=request.session.get('login').get('id')
    #评论文章id
    article_id=request.POST['article']
    #获取评论内容
    content=request.POST['content']
    #评论时间
    startime=timezone.now()
    #floor_id,为None标志为楼层评论
    floor_id=request.POST.get('floor_id',None)
    # 用户
    user=mo.User.objects.get(id=str(user_id))
    # 父评论id
    this_comment_id=request.POST.get('this_comment_id')
    # 更新评论
    update=models.Comment(user=user,
                   article=models.Article.objects.get(id=article_id),startime=startime,
                   father_id=str(father_id),content=content,
                    floor_id=str(floor_id))

    update.save()
    if father_id!=None:
        username=models.Comment.objects.get(id=update.id).user.username
        fathername=models.Comment.objects.get(id=father_id).user.username
        #获得是否为二级评论,如果为1就是二级评论，2为多级评论
        if father_id==floor_id:
            fathername=' '+fathername
        context={'fathername':fathername,'id':update.id,'startime':update.startime,'content':content,'username':username}
    # 更新评论关系，评论了谁
        models.to_Comment(user=user,to_user=models.Comment.objects.get(id=father_id).user,
                          comment=father_id,
                          startime=startime).save()
        # 更新评论关系，被谁评论
        models.to_Comment(user=models.Comment.objects.get(id=father_id).user,
                          to_user=user,to_comment=update.id,
                          startime=startime).save()
        return JsonResponse({'result':[context],'floor_id':floor_id})

    if floor_id==None:
        # 更新评论关系，评论了谁
        models.to_Comment(user=user,to_user=models.Article.objects.get(id=article_id).user,
                          comment=this_comment_id,
                          startime=startime).save()
        # 更新评论关系，被谁评论
        models.to_Comment(user=models.Article.objects.get(id=article_id).user,
                          to_user=user,to_comment=update.id,
                          startime=startime).save()
        # 文章对象，重新进入评论页面
        art=models.Article.objects.get(id=article_id)
        return redirect(art.get_absolute_url())

#楼中楼分页
def comment_paginator(request):
    floor_id=request.POST.get('floor_id')
    #请求页码
    num=request.POST.get('num','1')
    #获得子评论
    all_comment=models.Comment.objects.filter(floor_id=floor_id)
    # 分页父对象
    page=Paginator(all_comment,10)
    # 当前页对象
    page_list=page.page(int(num))
    number=page_list.number
    res_1=[]
    for i in page_list:
        #替换username，fathername
        fathername=models.Comment.objects.get(id=i.floor_id).user.username
        #区分标志
        if i.father_id==i.floor_id:
            fathername=' '+fathername
        res_1.append({'id':i.id,
                    'startime':i.startime,
                    'content':i.content,
                    'fathername':fathername,
                    'username':i.user.username}
                      )

    return JsonResponse({'page_list':res_1,'page_range':list(page.page_range),'page_num':number})


# 文章图片上传
def kind_upload(request):
    imgfile=request.FILES.get('upload_img',None)

    if imgfile:
        result=img_type(imgfile)
        return HttpResponse(json.dumps(result),content_type='application/json')

# 图片上传
def img_type(file):
    result={'error':0,'message':'上传失败'}
    # 允许上传文件类型
    type_valid= ['jpg', 'png', 'jpeg', 'gif', 'bmp']
    try:
        filename=re.search('\..+',file.name).group()[1:]
    except:
        pass
    if filename not in type_valid or (len(file)>5242880):
        result['error']=1
        return result
    else:
        filename_1=time.strftime('%Y%m%d%H%M%s')+file.name
        filename=os.path.join(settings.BASE_DIR,'static/media/',filename_1)
        with open(filename,'wb') as t:
           for i in file.chunks():
               t.write(i)
        del result['message']
        result['url']='/media/%s'%filename_1
        return result
#

# 发表文章提交
def article_submit(request,pk):
    user=mo.User.objects.get(id=request.session.get('login').get('id'))
    if user:
        title=request.POST.get('title')
        content=request.POST.get('content')
        startime=timezone.now()
        category=models.Category.objects.get(pk=pk)
        # 获得用户对象，session
        update=models.Article(title=title,
                       content=content,startime=startime,
                       category=category,user=user)
        update.save()
        return redirect(category.get_absolute_url())



# 搜索
def mysearch(request):
    return render(request,'bbsapp/mysearch.html')

# # 多图上传
# def webuploader(request):

bbs/templates/bbsapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	{%load staticfiles%}
	<script src="{%static 'text/js/jquery-2.1.3.min.js'%}"></script>
	<link rel="stylesheet" href="{%static 'text/css/font-awesome-4.7.0/css/font-awesome.min.css'%}" type="text/css">
	<link rel="stylesheet" href="{%static '/bootstrap/css/bootstrap.css'%}">
	<script src="{%static '/bootstrap/js/bootstrap.js'%}"></script>
	<link rel="stylesheet" href="{%static 'text/css/index_nav.css'%}">
	<script>
	var online_user={
	    'id':{{request.session.login.id}},
        'username':{{request.session.login.username}},
	}
</script>
	{%block href%}

	{%endblock href%}
</head>
<body>

	<div class="main">
		<div class="reflash_button "><i class='fa fa-refresh'></i></div>
		<div class="top_button "><a href='#top'><i class='fa fa-toggle-up'></i></a></div>

			<div class="navbar navbar-inverse navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				 <button class="navbar-toggle" data-toggle="collapse" data-target="#togglemenu">
		         	<span class="icon-bar"></span>
		         	<span class="icon-bar"></span>
		         	<span class="icon-bar"></span>
		         </button>

				<a href="#" class="navbar-brand">LOGO</a>
			</div>
			<div class="collapse navbar-collapse" id="togglemenu">
					<ul class="nav navbar-nav">
						<li class="active"><a href="{%url 'bbsapp:index'%}">首页</a></li>
							<li>
								<a href=" ">视频</a>
							</li>
							<li>
								<a href=" ">发现</a>
							</li>
							<li>
								<a href=" ">游戏</a>
							</li>
					</ul>
					<!-- <button class="btn btn-default navbar-btn">按钮</button> -->

					<form class="navbar-form navbar-left">
						<div class="form-group">
							<div class="input-group">
								<input type="text" name="" class="form-control">
								<span class="input-group-btn">
									<button class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
								</span>
							</div>

						</div>
					</form>
                	<ul class="nav navbar-nav navbar-left">
                            {%if request.session.login%}
							{%load myhome_tag%}
							{%get_user request.session.login.id as user%}
                            <li>
                                <a href=" ">{{request.session.login.username}}</a>
                            </li>
                            <li>
                                <a href="{{user.get_absolute_url}}">我的空间</a>
                            </li>
                            <li>
                            <a href="{%url 'login_in:out'%}">注销</a>
                            </li>
                            {%else%}
                            <li>
								<a href="{%url 'login_in:login'%}?next={{request.path}}">登陆</a>
							</li>
							<li>
								<a href="{%url 'login_in:register'%} ">注册</a>
							</li>
							{%endif%}
					</ul>
			</div>
		</div>
	</div>




			<!--<div class='top_container'>-->
				<!--<a href=" "><img src="{%static 'text/image/1.jpg.jpg'%} "></a>-->
				<!--<div class="search_line ">-->
					<!--<form>-->
						<!--<input type="text " placeholder="大家正在搜索 " />-->
					<!--</form>-->
					<!--<a href=" "><img id='search_icon' src="{%static 'text/image/search_icon.jpg' %}" /></a>-->
				<!--</div>-->
				<!--<div class="top_navall ">-->
					<!--<div class="top_login ">-->
						<!--<ul>-->

                            <!--{%if request.session.login%}-->
							<!--{%load myhome_tag%}-->
							<!--{%get_user request.session.login.id as user%}-->
                            <!--<li>-->
                                <!--<a href=" ">{{request.session.login.username}}</a>-->
                            <!--</li>-->
                            <!--<li class='list_line'>|</li>-->
                            <!--<li>-->
                                <!--<a href="{{user.get_absolute_url}}">我的空间</a>-->
                            <!--</li>-->
                            <!--<li class='list_line'>|</li>-->
                            <!--<li>-->
                            <!--<a href="{%url 'login_in:out'%}">注销</a>-->
                            <!--</li>-->
                            <!--{%else%}-->
                            <!--<li>-->
								<!--<a href="{%url 'login_in:login'%}?next={{request.path}}">登陆</a>-->
							<!--</li>-->
							<!--<li class='list_line'>|</li>-->
							<!--<li>-->
								<!--<a href="{%url 'login_in:register'%} ">注册</a>-->
							<!--</li>-->
							<!--{%endif%}-->
						<!--</ul>-->
					<!--</div>-->
					<!--<div class="top_nav ">-->
						<!--<ul>-->
							<!--<li>-->
								<!--<a href="{%url 'bbsapp:index'%}">首页</a>-->
							<!--</li>-->
							<!--<li>-->
								<!--<a href=" ">视频</a>-->
							<!--</li>-->
							<!--<li>-->
								<!--<a href=" ">发现</a>-->
							<!--</li>-->
							<!--<li>-->
								<!--<a href=" ">游戏</a>-->
							<!--</li>-->
						<!--</ul>-->
					<!--</div>-->
				<!--</div>-->
			<!--</div>-->
		{%block center%}

		{%endblock center%}
    </div>
</body>

</html>

bbs/templates/bbsapp/border.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/home/wangzhuo/mygit/bbs/static/text/css/border.css">
</head>
<body>
    <div class="box4">
           <h1>Sample Box</h1>
           <img src="http://www.wpthemegenerator.com/wp-content/uploads/2012/06/Image.jpg">
            <p>
             Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam luctus consectetur dolor a porttitor. Curabitur id sem sed ante fringilla pulvinar et id lectus. Nullam justo ipsum, hendrerit ut commodo nec, pellentesque nec erat. Pellentesque pharetra.
           </p>
           <br />
           <a href="http://www.designshock.com/"> DesignShock.com </a>
           <div class="shr_box4"></div>
           <div class="shl_box4"></div>
    </div>
</body>
</html>

bbs/templates/bbsapp/mysearch.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<form method='get' action="/search/" target="_blank">
    <input type="text" name="q">
    <input type="submit" value="查询">
</form>

</body>
</html>