blog/blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blogapp.urls',namespace='blogapp',app_name='blogapp')),
    url(r'^', include('comment.urls',namespace='comment',app_name='comment')),
    url(r'^', include('text.urls',namespace='text',app_name='text')),
    
]

blog/blogapp/urls.py
from django.conf.urls import url
from blogapp import views
urlpatterns=[
    url(r'^$',views.indexview.as_view(),name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',views.detail,name='detail'),
    url(r'^post/(?P<year>[0-9]{4})(?P<month>[0-9]+)$',views.guidang,name='guidang'),
    url(r'^post/(?P<pk>[0-9]+)$',views.categoryview.as_view(),name='fenlei'),
    url(r'^post/tag/(?P<pk>[0-9]+)$',views.tag,name='tag'),
]

blog/comment/urls.py
from django.conf.urls import url
from comment import views
urlpatterns=[
    url(r'^comment/(\d+)',views.post_comment,name='post_comment'),
]

blog/blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags


# Create your models here.
# class mymanager(models.Manager):
#     def create(self,s1,s2,s3,s4,s5,s6):
#         b=Post()
#         b.title=s1
#         b.content=s2
#         b.startime=s3
#         b.endtime=s4
#         b.other=s5
#         b.tag=s6
#         return b

#文章分类
class Category(models.Model):
    name=models.CharField(max_length=90)
    def get_absolute_url(self):
        print("ss")
        return reverse('blogapp:fenlei',kwargs={"pk":self.pk})
    def __str__(self):
        return self.name

#文章标签
class Tag(models.Model):
    name=models.CharField(max_length=90)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('blogapp:tag',kwargs={'pk':self.pk})

class Post(models.Model):
    # book1=models.manager.Manager()
    title=models.CharField(max_length=70)
    content=models.TextField()
    startime=models.DateTimeField()
    endtime=models.DateTimeField()
    #摘要
    other=models.CharField(max_length=200,blank=True)
    #外键
    category=models.ForeignKey(Category)
    #与标签多对多
    tag=models.ManyToManyField(Tag,blank=True)
    #作者关联　
    user=models.ForeignKey(User)
    #阅读量
    views=models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.title
    #通过post对象在模板中调用get_absolute_url方法,得到urls中url,并传入post的pk参数
    #直接获取页面，动态拼接url
    def get_absolute_url(self):
        return reverse('blogapp:detail',kwargs={'pk':self.pk})
    
    #定义阅读量方法
    def plus_views(self):
        self.views+=1
        self.save(update_fields=['views'])

    #自动获取摘要{{ post.body|truncatechars:54 }}(过滤器在模板中直接使用)
    def save(self,*args,**kwargs):
        if not self.other:
            md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.other= strip_tags(md.convert(self.content))[:24]
        super(Post,self).save(*args,**kwargs)


    #定义排序方式
    class Meta:
        ordering=['-startime']

blog/comment/models.py
from django.db import models

# Create your models here.

class comment(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(max_length=150)
    url=models.URLField(blank=True)
    content=models.TextField()
    #创建对象自动生成当前时间
    create_time=models.DateTimeField(auto_now_add=True)
    post=models.ForeignKey('blogapp.Post')
    def __str__(self):
        return self.content[:20]

blog/blogapp/views.py
from django.shortcuts import render,get_object_or_404
from django.http import *
from blogapp import models
from markdown import markdown
from comment.forms import commentForms
from django.views.generic import ListView
from django.core.paginator import Paginator
# Create your views here.
# def index(request):
#     post=models.Post.objects.all()
#     context={'post':post}
#     return render(request,'blogapp/index.html',context) 

def detail(request,pk):
    post=get_object_or_404(models.Post,pk=pk)
    post.plus_views()
    post.content=markdown(post.content,extensions=[
                                    'markdown.extensions.extra',
                                    'markdown.extensions.codehilite',
                                    'markdown.extensions.toc',
    ])
    comment_res=post.comment_set.all().order_by('-create_time')
    form=commentForms()
    return render(request,'blogapp/detail.html',{"comment":comment_res,'form':form,'post':post})          

#按月归档
def guidang(request,year,month):
    post=models.Post.objects.filter(startime__year=year,startime__month=month)
    return render(request,'blogapp/index.html',context={'post':post})

def tag(request,pk):
    tag_1=get_object_or_404(models.Tag,pk=pk)
    tag_1=models.Post.objects.filter(tag=tag_1)
    return render(request,'blogapp/index.html',context={'post':tag_1})
# 分类
# def fenlei(request,pk):
#     #两种方式，一种利用category类对象调用类中reverse获取url，
#     #一种利用url反向解析获取url
#     post=get_object_or_404(models.Category,pk=pk)
#     post=models.Post.objects.filter(category=post)
#     return render(request,'blogapp/index.html',context={'post':post})

    #利用category的获取外键方法获取post对象
    # post=mdels.Category.objects.get(name=category)
    # post=post.post_set.all()


#视图类可以用继承减少重复代码，如获得分页效果和重复获得文章对象
class indexview(ListView):
    #拿到post对象
    model=models.Post
    #指定模板
    template_name='blogapp/index.html'
    #定义对象列表名称相当于context名称
    context_object_name='post'
    #设置分页
    paginate_by=2

class categoryview(indexview):
    #视图类获得对象需要调用get_queryset方法，复写方法添加筛选条件
    def get_queryset(self):
        cate=get_object_or_404(models.Category,pk=self.kwargs.get('pk'))
        #调用父类方法获得post对象
        return super(categoryview,self).get_queryset().filter(category=cate)

#自定义分类函数
class indexview(ListView):
    model=models.Post
    template_name='blogapp/index.html'
    context_object_name='post'
    paginate_by=2
    #视图函数中context传参使用get_context_data
    def get_context_data(self,**kwargs):
        #获得context对象
        context=super(indexview,self).get_context_data(**kwargs)
        #分页对象
        paginator=context.get('paginator')
        #当前也对象
        page=context.get('page_obj')
        #是否分页
        is_paginated=context.get('is_paginated')

        res=self.mypaginator(paginator,page,is_paginated)
        context.update(res)
        return context
    
    

    def mypaginator(self,paginator,page,is_paginated):
        left,right=[],[]
        left_dian,right_dian=False,False
        first,last=False,False
        nowpage_num=page.number
        page_list=paginator.page_range
        all_page_number=paginator.num_pages
        if nowpage_num==1:
            right=page_list[nowpage_num:nowpage_num+2]
            if right[-1]<all_page_number-1:
                right_dian=True
            if right[-1]<all_page_number:
                last=True
        elif nowpage_num==all_page_number:
            left=page_list[nowpage_num-3:nowpage_num-1]
            if left[0]>page_list[1]:
                left_dian=True
            if left[0]>page_list[0]:
                first=True
        else:
            left=page_list[nowpage_num-2:nowpage_num-1]
            right=page_list[nowpage_num:nowpage_num+2]
            if right[-1]<all_page_number-1:
                right_dian=True
            if right[-1]<all_page_number:
                last=True
            if left[0]>page_list[1]:
                left_dian=True
            if left[0]>page_list[0]:
                first=True
        context={
            'left':left,
            'right':right,
            'left_dian':left_dian,
            'right_dian':right_dian,
            'first':first,
            'last':last
        }
        return context
            

            










        

   

blog/templates/blogapp/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

blog/templates/blogapp/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    {%load staticfiles%}
    <link rel="stylesheet" href="{% static 'blogapp/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static '/blogapp/css/pace.css' %}">
    <link rel="stylesheet" href="{% static '/blogapp/css/custom.css'%}">

    <!-- js -->
    <script src="{% static 'blogapp/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blogapp/js/bootstrap.min.js' %}"></script>
    <script src="{%static '/blogapp/js/pace.min.js'%}"></script>
    <script src="{%static '/blogapp/js/modernizr.custom.js'%}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="/"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="/" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
            {%block center%}
            
            {%endblock center%}
            </main>
            <aside class="col-md-4">
            {%block bottom%}
            {%endblock bottom%}
               
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{%static '/blogapp/js/script.js'%}"></script>

</body>
</html>

blog/templates/blogapp/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

blog/templates/blogapp/detail.html
 {%extends 'blogapp/index.html'%} {%block center%}
<article class="post post-1">
    <header class="entry-header">
        <h1 class="entry-title">{{post.title}}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="{{post.get_absolute_url}}">{{post.category.name}}</a></span>
            <span class="post-date"><a href="{{post.get_absolute_url}}"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">{{post.startime}}</time></a></span>
            <span class="post-author"><a href="{{post.get_absolute_url}}">{{post.user}}</a></span>
            <span class="comments-link"><a href="{{post.get_absolute_url}}">{{post.comment_set.count}} 评论</a></span>
            <span class="views-count"><a href="{{post.get_absolute_url}}">{{post.views}}阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{post.content | safe}}
    </div>
</article>
<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'comment:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="{{ form.name.id_for_label }}">名字：</label>
                {{ form.name }} {{ form.name.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                {{ form.email }} {{ form.email.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.url.id_for_label }}">URL：</label>
                {{ form.url }} {{ form.url.errors }}
            </div>
            <div class="col-md-12">
                <label for="{{ form.text.id_for_label }}">评论：</label>
                {{ form.content}} {{ form.content.errors }}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div> <!-- row -->
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{post.comment_set.count}}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {%for list in comment%} 
            <li class="comment-item">
                <span class="nickname">{{list.name}}</span>
                <time class="submit-date" datetime="{{list.create_time}}">{{list.create_time}}</time>
                <div class="text">
                   {{list.content}} 
                </div>
            </li>
            {%endfor%}
                    </ul>
    </div>
</section>
</main>
{%endblock center%} {%block bottom%}
<div class="widget widget-content">
    <h3 class="widget-title">文章目录</h3>
    <ul>
        <li>
            <a href="#">教程特点</a>
        </li>
        <li>
            <a href="#">谁适合这个教程</a>
        </li>
        <li>
            <a href="#">在线预览</a>
        </li>
        <li>
            <a href="#">资源列表</a>
        </li>
        <li>
            <a href="#">获取帮助</a>
        </li>
    </ul>
</div>
{%endblock bottom%}

blog/templates/blogapp/index.html
{%extends 'blogapp/base.html'%} {%block center%} {%for list in post%}
<article class="post post-{{list.pk}}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{list.get_absolute_url}}">{{list.title}}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="{{list.get_absolute_url}}">{{list.category.name}}</a></span>
            <span class="post-date"><a href="{{list.get_absolute_url}}"><time class="entry-date" datetime="{{list.startime}}">{{list.startime}}</time></a></span>
            <!-- #作者 -->
            <span class="post-author"><a href="{{list.get_absolute_url}}">{{list.user}}</a></span>
            <span class="comments-link"><a href="{{list.get_absolute_url}}">{{list.comment_set.count}} 评论</a></span>
            <span class="views-count"><a href="{{list.get_absolute_url}}">{{list.views}}阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <!-- 摘要 -->
        <p>{{list.other}}.....</p>

        <div class="read-more cl-effect-14">
            <a href="{{list.get_absolute_url}}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{%empty%}
<div class="no-post">暂时没有文章发布哦!</div>
{%endfor%}


{% if is_paginated %}
<div id="pagination" style="text-align:center">
    {% if first %}
    <a href="?page=1">1</a>
    {% endif %} {% if left %} {% if left_dian%}
    <span>...</span>
    {% endif %} {% for i in left %}
    <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %} {% endif %}
    <a href="?page={{ page_obj.number }}" style="background: rgb(116, 79, 187)">{{ page_obj.number }}</a>
    {% if right %} {% for i in right %}
    <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %} {% if right_dian%}
    <span>...</span>
    {% endif %} {% endif %} {% if last %}
    <a class='current-page' href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
    {% endif %}
</div>
{% endif %} {%endblock center%} {%block bottom%} {%load blog_tags%}
<div class="widget widget-recent-posts">
    <h3 class="widget-title">最新文章</h3>
    <ul>
        {%get_newtitle as get_newtitle%} {%for list in get_newtitle%}
        <li>
            <span class="glyphicon glyphicon-chevron-right"></span><a href="{{list.get_absolute_url}}">{{list.title}}</a>
        </li>
        {%empty%} 当前没有文章哦！ {%endfor%}
    </ul>
</div>
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {%get_guidang as get_guidang%} {%for list in get_guidang%}
        <li>
            <span class="glyphicon glyphicon-chevron-right"></span><a href="{%url 'blogapp:guidang' list.year list.month%}">{{list.year}}年{{list.month}}月{{list.day}}日</a>
        </li>

        {%endfor%}

    </ul>
</div>

<div class="widget widget-category">
    <h3 class="widget-title">分类</h3>
    <ul>
        {%get_category as get_category%} {%for list_1 in get_category%}
        <li>
            <span class="glyphicon glyphicon-chevron-right"></span> <a href="{{list_1.get_absolute_url}}">{{list_1.name}}<span
                    class="{{list_1.num_count}}">({{list_1.num_count}})</span></a>
        </li>
        {%endfor%}
    </ul>
</div>

<div class="widget widget-tag-cloud">
    <h3 class="widget-title">标签云</h3>
    {%get_tag as get_tag%}
    <ul>
        {%for i in get_tag%}
        <li>
            <a href="{{i.get_absolute_url}}">{{i.name}}</a>
        </li>
            </ul>
            {%endfor%}
</div>
<div class="rss">
    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
</div>
{%endblock bottom%}