bbs/bbs/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('login_in.urls',namespace='login_in')),
    url(r'^', include('bbsapp.urls',namespace='bbsapp')),
    #验证码url
    url(r'^captcha/', include('captcha.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'', include('ckeditor_uploader.urls')),
    url(r'^', include('bbsapp.urls',namespace='kind')),
    url(r'^', include('myhome.urls',namespace='myhome')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 没有这一句无法显示上传的图片

bbs/login_in/urls.py
from django.conf.urls import url
from login_in import views
from bbs import settings

urlpatterns=[
    # url(r'^register$',views.register,name='register'),
    url(r'^register$',views.send.as_view(),name='register'),
    url(r'^login$',views.login.as_view(),name='login'),
    url(r'^login/out$',views.login_out,name='out'),
    url(r'^login/newpassword/$',views.newpassword.as_view(),name='newpassword'),
    #验证码自带视图，不需要写视图函数
]

bbs/login_in/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

class User(AbstractUser):
    #头像
    image_url=models.ImageField(upload_to='media',null=True)
    email=models.EmailField(blank=False,unique=True)
    #国家
    country=models.ForeignKey('Country',null=True)
    #注册时间
    register_time=models.DateTimeField(auto_now_add=True,null=True)
    #登陆时间
    login_time=models.DateTimeField(auto_now_add=True,null=True)
    # 获得个人空间url
    def get_absolute_url(self):
       return reverse('myhome:index',kwargs={'pk':self.pk})

    def get_absolute_url_index(self):
        return reverse('bbsapp:index')

    class Meta(AbstractUser.Meta):
        pass

class Country(models.Model):
    name=models.CharField(max_length=20)

class history(models.Model):
    # 历史纪录
    article_history=models.IntegerField()
    # 用户
    user=models.ForeignKey(User)
    # 时间
    startime=models.DateTimeField(auto_now_add=True,null=True)

bbs/login_in/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *
from captcha.fields import CaptchaField
from django.core.exceptions import ValidationError
import re
from django.forms import fields,widgets


#注册
class registerform(forms.Form):
    username=fields.CharField(max_length=30,
                                label='用户名',
                              error_messages={'required':'用户名不能为空！'},
                              widget=widgets.TextInput(attrs={'class':'username','placeholder':'请输入用户名'}))
    password=fields.CharField(max_length=30,
                   error_messages={'required':'密码不能空!'},
                   widget=widgets.PasswordInput(attrs={'class':'pass','placeholder':'请输入密码'}) 
    )
    password2=fields.CharField(max_length=30,
                   error_messages={'required':'密码不能空!'},
                   widget=widgets.PasswordInput(attrs={'class':'pass','placeholder':'请确认密码'}) 
    )
    email=fields.EmailField(max_length=30,
                   error_messages={'required':'邮箱不能空!'},
                    )
    country=fields.CharField(initial=1,widget=widgets.Select(choices=((1,'美国'),(2,'日本'))))
    
    image_url=fields.ImageField(required=False)


    #验证码生成
    captcha=CaptchaField()    
    
    def clean_username(self):
        #cleaned_data为表单内容的字典
        name=self.cleaned_data['username']
        if len(name)<1 or len(name)>30: 
            raise ValidationError('用户名必须在1-30字符内!')
        if User.objects.filter(username=name):
            raise ValidationError('用户名已存在!')
            #必须return 表单内容
        return name
        
    def clean_password(self):
        pass1=self.cleaned_data['password']
        if len(pass1)<6 or len(pass1)>30:
            raise ValidationError('密码长度在6-30字符内')
        return pass1

    def clean_password2(self):
        pass2=self.cleaned_data['password2']
        pass1=self.cleaned_data['password']
        if pass1!=pass2:
            raise ValidationError('两次密码不一致!')
        return pass2
    def clean_email(self):
        em=self.cleaned_data['email']
        if User.objects.filter(email=em):
            raise ValidationError('邮箱已被注册！')
        return em


#登录功能
class login_1(forms.Form):
    username=fields.CharField(max_length=30,
                            error_messages={'required':'用户名不能为空!'},
                            widget=widgets.TextInput(attrs={'class':'username','placeholder':'请输入用户名:'}))
    password=fields.CharField(max_length=30,
                              error_messages={'required':'密码不能为空！'},
                              widget=widgets.PasswordInput(attrs={'class':'password','placeholder':'请输入密码：'}))
    #记住用户名
    rember=fields.CharField(required=False,
                                widget=widgets.CheckboxInput())

    #验证用户名
    def clean_username(self):
        user=self.cleaned_data.get('username')
        if len(user)>29:
            raise ValidationError('用户名不存在！')
        if not User.objects.filter(username=user):
            raise ValidationError('用户名不存在!')
        return user
    def clean_password(self):
        user=self.cleaned_data.get('username')
        pass1=self.cleaned_data.get('password')
        if user:
            if pass1!=User.objects.get(username=user).password:
                raise ValidationError('用户名或密码错误!')
        return pass1

        



    
            
            

bbs/login_in/views.py
from django.core.cache import cache
from django.shortcuts import render,redirect
from django.views.generic import ListView
from login_in import models
from django.http import JsonResponse, HttpResponse
from bbs import settings
from django.core.mail import send_mail
import random
# Create your views here.


#注册页面
class send(ListView):
    def get(self, request, *args, **kwargs):
        username=request.GET.get('username')
        email=request.GET.get('email')
        if username:
            if models.User.objects.filter(username=username):
                return JsonResponse({'errors':'用户名以存在！'})
        if email:
            if models.User.objects.filter(email=email):
                return JsonResponse({'errors':'邮箱以被注册！'})
        return  render(request,'login_in/index.html')

    def post(self,request,*args,**kwargs):
        username=request.POST.get('username')
        email=request.POST.get('email')
        password=request.POST.get('password')
        update=models.User(username=username,
                    email=email,
                    password=password)
        update.save()
        return redirect(update.get_absolute_url_index())

# 登陆页面
class login(ListView):
    # 验证
    def post(self,request,*args,**kwargs):
        username=request.POST.get('username')
        password=request.POST.get('password')
        true_name=models.User.objects.filter(username=username)
        if true_name:
            if true_name[0].password==password:
                # 传递在线用户id和username
                context_session={'username':true_name[0].username,'id':true_name[0].id}
                # 存入登陆信息
                request.session['login']=context_session
                # 获取登陆前的网址
                prev_url=request.POST.get('next')
                print(prev_url)
                return redirect(prev_url)
            else:
                return render(request,'login_in/index.html',context={'errors':'用户名或密码错误！'})
        else:
            return render(request,'login_in/index.html',context={'errors':'用户名不存在！'})

    # 返回空页面
    def get(self, request, *args, **kwargs):
        next=request.GET.get('next')
        return render(request,'login_in/index.html',context={'next':next})

def login_out(request):
    try:
        del request.session['login']
    except:
        pass
    return redirect('/')




# 邮箱密码zhaohui
class newpassword(ListView):
    def post(self,request,*args,**kwargs):
        # 判断验证马
        if request.POST.get('yanzhengma'):
            # 拿到缓存邮箱的验证码
            email=cache.get(request.POST.get('email'))
            # 判断邮箱是否失效90s，并判断验证马
            if email and request.POST.get('yanzhengma')==email:
                return render(request,'login_in/new_password.html',context={'next_2':'right'})
            # 返回错误信息
            else:
                return render(request,'login_in/new_password.html',context={'next':email,'result':'not right'})
        # 判断邮箱是否存在，
        else:
            email=request.POST.get('email')
            try:
                models.User.objects.get(email=email)
            except:
                return render(request,'login_in/new_password.html',context={'result':'该邮箱为注册'})
            else:
                # 邮箱存在发送验证马
                try:
                    from .task import send_email
                    send_email.delay(email)
                except Exception as e:
                    print(e)
                return render(request,'login_in/new_password.html',context={'next':email})
    # 默认页面
    def get(self,request,*args,**kwargs):
        return render(request,'login_in/new_password.html')





#
# def register(request):
#     if request.method=='POST':
#         form=forms.registerform(request.POST,request.FILES)
#         if form.is_valid():
#             #对图片重命名
#             img_id=models.User.objects.all().order_by('-id')
#             try:
#                 request.FILES.get('image_url').name=str(int(img_id[0].id)+1)+'.jpg'
#             except:
#                 pass
#             #进行自定义验证，并获得表单字典格式
#             form_con=form.clean()
#             models.User(
#                 username=form_con['username'],
#                 password=form_con['password'],
#                 email=form_con['email'],
#                 country=models.Country.objects.get(pk=form_con['country']),
#                 image_url=form.cleaned_data['image_url'],
#                 register_time=timezone.now()
#
#             ).save()
#             user_online=models.User.objects.filter(username=form_con['username'])
#             return render(request,'bbsapp/index.html',context={'user_online':user_online[0]})
#         else:
#             # error=form.errors
#             #不合法,返回form对象,即含有错误信息的表单
#             return render(request,'login_in/register.html',context={'form':form})
#     else:
#         form=forms.registerform()
#     return render(request,'login_in/register.html',context={'form':form})
#
#登录




# def login(request):
#     if request.method=='POST':
#         form=forms.login_1(request.POST)
#         if form.is_valid():
#             #验证自定义方法，返回表单字典格式数据
#             form_con=form.clean()
#             #登录对象,get返回一个对象，回报异常，filter返回列表不报异常
#             user_update=models.User.objects.filter(username=form_con['username'])[0]
#             user_update.login_time=timezone.now()
#             #记录登录时间，更新指点个字段
#             user_update.save(update_fields=['login_time'])
#             #登录成功将登录对象传递值首页
#             return render(request,'bbsapp/index.html',context={'user_online':user_update})
#
#         else:
#             print('sssssssssssssssssssssssssssssssssssssssss')
#             return render(request,'login_in/login.html',context={'form':form})
#     else:
#         form=forms.login_1()
#     return render(request,'login_in/login.html',context={'form':form})
#









    

bbs/templates/login_in/index.html
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Home</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />
  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />
        {%load staticfiles%}
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
	<link rel="stylesheet" href="{%static 'login_in/css/animate.css'%}">
	<link rel="stylesheet" href="{%static 'login_in/css/icomoon.css'%}">
	<link rel="stylesheet" href="{%static 'login_in/css/themify-icons.css'%}">
	<link rel="stylesheet" href="{%static 'login_in/css/bootstrap.css'%}">
	<link rel="stylesheet" href="{%static 'login_in/css/magnific-popup.css'%}">
	<link rel="stylesheet" href="{%static 'login_in/css/owl.carousel.min.css'%}">
	<link rel="stylesheet" href="{%static 'login_in/css/owl.theme.default.min.css'%}">
	<link rel="stylesheet" href="{%static 'login_in/css/style.css'%}">
	<script src="{%static 'login_in/js/modernizr-2.6.2.min.js'%}"></script>
	<!--[if lt IE 9]>
	<script src="{%static 'login_in/js/respond.min.js'%}"></script>
	<![endif]-->
        <style>
        .errorlist {
            color: red;
        }
    </style>
		 <script>
     function checkUser(data) {
         var reg = /^[\u4e00-\u9fff\w]{1,16}$/;
         if (reg.test($(data).val()) == false) {

             $(data).next().html('用户名格式错误!')
             return false;
         } else {
             $(data).next().html('')
             return true;
         }
     }

     /*密码验证*/
     function checkPwd(data) {
         var reg = /^[a-zA-Z0-9\.]{4,10}$/;
         if (reg.test($(data).val()) == false) {
             $(data).next().html('密码格式错误！')
             return false;
         } else {
             $(data).next().html('')
             return true;
         }
     }

     function checkRepwd(data) {
         var pwd = $('.pwd').val();
         if (pwd != $(data).val()) {
             $(data).next().html('两次密码输入不一致！')
             return false;
         } else {
             $(data).next().html('')
             return true;
         }
     }

     /*验证邮箱*/
     function checkEmail(data) {
         var reg = /^\w+@\w+(\.[a-zA-Z]{2,3}){1,2}$/;
         if (reg.test($(data).val()) == false) {
             $(data).next().html('邮箱格式错误!')
             return false;
         } else {
             $(data).next().html('')
             return true;
         }
     }

     /*验证手机号码*/
     // function checkMobile(){
     //     var mobile=$("mobile");
     //     var mobileId=divId("mobile_prompt");
     //     var regMobile=/^1\d{10}$/;
     //     if(regMobile.test(mobile)==false){
     //         mobileId.innerHTML="手机号码不正确，请重新输入";
     //         return false;
     //         }
     //         mobileId.innerHTML="";
     //         return true;
     //     }

     function send_user(data) {
        if($(data).next().html()==''){

            username=$(data).val()
            $.get('/register',{'username':username},function (data_2) {
                $(data).next().html(data_2.errors)
            })
            return true
        }
     }
     function last() {
        $.each($('form span'),function (index,index2) {
           if(index2.val()!=''){
               return false
           }
           return true
        })
     }

     //提交前静态验证
     function check() {
         var check = checkUser('.username') && checkPwd('.pwd') && checkRepwd('.repwd') &&  last();
         return check;

     }
 </script>
	</head>
	<body>
		
	<div class="gtco-loader"></div>
	<div id="page">
	<div class="page-inner">
	<nav class="gtco-nav" role="navigation">
		<div class="gtco-container">
			
			<div class="row">
				<div class="col-sm-4 col-xs-12">
					<div id="gtco-logo"><a href="index.html">Splash <em>.</em></a></div>
				</div>
				<div class="col-xs-8 text-right menu-1">
					<ul>
						<li><a href="features.html">Features</a></li>
						<li><a href="tour.html">Tour</a></li>
						<li class="has-dropdown">
							<a href="#">Dropdown</a>
							<ul class="dropdown">
								<li><a href="#">Web Design</a></li>
								<li><a href="#">eCommerce</a></li>
								<li><a href="#">Branding</a></li>
								<li><a href="#">API</a></li>
							</ul>
						</li>
						<li><a href="pricing.html">Pricing</a></li>
						<li><a href="contact.html">Contact</a></li>
						<li class="btn-cta"><a href="#"><span>Get started</span></a></li>
					</ul>
				</div>
			</div>
			
		</div>
	</nav>
	
	<header id="gtco-header" class="gtco-cover" role="banner" style="background-image: url(/static/login_in/images/img_ig.jpg)">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					<div class="row row-mt-15em">
						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
							<span class="intro-text-small">Welcome to Splash</span>
							<h1></h1>
						</div>
						<div class="col-md-4 col-md-push-1 animate-box" data-animate-effect="fadeInRight">
							<div class="form-wrap">
								<div class="tab">
									<ul class="tab-menu">
										<li class="active gtco-first"><a href="#" data-tab="signup">注册</a></li>
										<li class="gtco-second"><a href="#" data-tab="login">登陆</a></li>
									</ul>
									<div class="tab-content">
										<div class="tab-content-inner active" data-content="signup">
											<form action="/register" method="post" onsubmit="return check()">
												<div class="row form-group">
													<div class="col-md-12">
														<label for="username">用户名</label>
														<!--<input type="text" class="form-control" id="username">-->
														<input type="text" class="username form-control" name="username" onkeyup="checkUser('.username')" onchange="send_user('.username')"/>
														<span ></span>
													</div>
												</div>
												<div class="row form-group">
													<div class="col-md-12">
														<label for="username">邮箱</label>
														<!--<input type="text" class="form-control" id="username">-->
														<input type="text"  name="email" class="email form-control" onkeyup="checkEmail('.email')" onchange="send_user('.email')">
														<span ></span>
													</div>
												</div>

												<div class="row form-group">
													<div class="col-md-12">
														<label for="password">密码</label>
														<!--<input type="password" class="form-control" id="password">-->
														<input type="password" class="pwd form-control" name="password"
															   onkeyup="checkPwd('.pwd')" />
													</div>
												</div>
												<div class="row form-group">
													<div class="col-md-12">
														<label for="password2">确认密码</label>
														<!--<input type="password" class="form-control" id="password2">-->
														<input type="password" class="repwd form-control" name="pwdc" onkeyup="checkRepwd('.repwd')"/>
														<span ></span>
													</div>
												</div>

												<div class="row form-group">
													<div class="col-md-12">
														<input type="submit" class="btn btn-primary" value="注册">
													</div>
												</div>
											</form>
										</div>

										<div class="tab-content-inner" data-content="login">
											<form class="form" action="{% url 'login_in:login' %}" method="post" >
												<div class="row form-group">
													<div class="col-md-12">
														<label for="username">用户名</label>
														<!--<input type="text" class="form-control" id="username">-->
														<input type="username" name="username" class="username form-control"><span>{{errors}}</span>
													</div>
												</div>
												<div class="row form-group">
													<div class="col-md-12">
														<label for="password">密码</label>
														<!--<input type="password" class="form-control" id="password">-->
														<input type="password" name="password"  class="form-control">
														<input type="hidden" value="{{next}}" name="next">
													</div>
												</div>

												<div class="row form-group">
													<div class="col-md-12">
														<input type="submit" class="btn btn-primary" value="登陆">
													</div>
												</div>
											</form>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>


				</div>
			</div>
		</div>
	</header>



		</div>
	</footer>
	</div>

	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="{%static 'login_in/js/jquery.min.js'%}"></script>
	<!-- jQuery Easing -->
	<script src="{%static 'login_in/js/jquery.easing.1.3.js'%}"></script>
	<!-- Bootstrap -->
	<script src="{%static 'login_in/js/bootstrap.min.js'%}"></script>
	<!-- Waypoints -->
	<script src="{%static 'login_in/js/jquery.waypoints.min.js'%}"></script>
	<!-- Carousel -->
	<script src="{%static 'login_in/js/owl.carousel.min.js'%}"></script>
	<!-- countTo -->
	<script src="{%static 'login_in/js/jquery.countTo.js'%}"></script>
	<!-- Magnific Popup -->
	<script src="{%static 'login_in/js/jquery.magnific-popup.min.js'%}"></script>
	<script src="{%static 'login_in/js/magnific-popup-options.js'%}"></script>
	<!-- Main -->
	<script src="{%static 'login_in/js/main.js'%}"></script>
	</body>
</html>

bbs/templates/login_in/login.html
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>登录</title>
    <!--<link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">-->
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3>登录</h3>
                <form class="form" action="{% url 'login_in:login' %}" method="post" >
                    <label for="">用户名:</label>
                    <input type="username" name="username" class="username"><span>{{errors}}</span>
                    <br>
                    <label for="">密码:</label>
                    <input type="password" name="password" >
                    <input type="hidden" value="{{next}}" name="next">
                    <br>
                    <input type="submit" value="登陆">
                </form>
                <div class="flex-left top-gap text-small">
                    <!-- 登录按钮 -->
                    <!-- <div class="unit-2-3"><span>没有账号？<a href="{% url 'login_in:register' %}">立即注册</a></span></div> -->
                    <!-- <div class="unit-1-3 flex-right"><span><a href="reset_password.html">忘记密码？</a></span></div> -->
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

bbs/templates/login_in/new_password.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <style type="text/css">
        * {
            margin: 0;
            padding: 0;
        }

        .send {
            width: 250px;
            margin: 0 auto;
        }

        .send input {
            display: block;
            width: 200px;
            font: 400 16px/30px "微软雅黑";
            outline: none;
            border: none;
        }
        .send button {
            height: 30px;
            border: none;
            outline: none;
            font: 400 16px/30px "微软雅黑";
            text-align: center;
        }
    </style>
    <script type="text/javascript">
          function checkEmail(data) {
         var reg = /^\w+@\w+(\.[a-zA-Z]{2,3}){1,2}$/;
         if (reg.test($(data).val()) == false) {
             $(data).next().html('邮箱格式错误!')
             return false;
         } else {
             $(data).next().html('')
             return true;
         }
        }
        // function yanzheng() {
        //    if($('.yanzheng').val()==null){
        //       return false
        //    }
        //    else {
        //        return true
        //    }
        // }
        function check() {
            var result=checkEmail('.email')
            return result
        }
    </script>
</head>
<body>
<div id="send">
    {%if result%}
    <span>{{result}}</span>
    {%endif%}
    <!--如果邮箱不存在-->
    {%if not next and not next_2%}
    <form action="{%url 'login_in:newpassword'%}" method="post" onsubmit="return check()">
    <label for="">请输入邮箱:</label>
    <input type="text" name="email" class="email" onkeyup="checkEmail('.email')">
        <br>
        <!--<label for="">请输入验证ma:</label>-->
        <!--<input type="text" name="yanzheng" class="yanzheng" >-->
    <span></span>
    <button type="submit"> send</button>
    </form>
    <!--如果验证码正确存在-->
    {%elif next_2%}
    <span>{{next_2}}</span>
    {%else%}
        <form action="{%url 'login_in:newpassword'%}" method="post">
        <label for="">yanzhengma</label>
        <input type="text" name="yanzhengma">
            <button type="submit">send</button>
            <input type="hidden" value="{{next}}" name="email">
            </form>
        {%endif%}
    <br>
</div>
</body>
</html>

bbs/templates/login_in/register.html
<!doctype html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport"
       content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
 <meta http-equiv="X-UA-Compatible" content="ie=edge">
 <title>Document</title>
 {%load staticfiles%}
 <script src="{%static 'text/js/jquery-2.1.3.min.js'%}"></script>
 <script>
     function checkUser(data) {
         var reg = /^[\u4e00-\u9fff\w]{1,16}$/;
         if (reg.test($(data).val()) == false) {

             $(data).next().html('用户名格式错误!')
             return false;
         } else {
             $(data).next().html('')
             return true;
         }
     }

     /*密码验证*/
     function checkPwd(data) {
         var reg = /^[a-zA-Z0-9\.]{4,10}$/;
         if (reg.test($(data).val()) == false) {
             $(data).next().html('密码格式错误！')
             return false;
         } else {
             $(data).next().html('')
             return true;
         }
     }

     function checkRepwd(data) {
         var pwd = $('.pwd').val();
         if (pwd != $(data).val()) {
             $(data).next().html('两次密码输入不一致！')
             return false;
         } else {
             $(data).next().html('')
             return true;
         }
     }

     /*验证邮箱*/
     function checkEmail(data) {
         var reg = /^\w+@\w+(\.[a-zA-Z]{2,3}){1,2}$/;
         if (reg.test($(data).val()) == false) {
             $(data).next().html('邮箱格式错误!')
             return false;
         } else {
             $(data).next().html('')
             return true;
         }
     }

     /*验证手机号码*/
     // function checkMobile(){
     //     var mobile=$("mobile");
     //     var mobileId=divId("mobile_prompt");
     //     var regMobile=/^1\d{10}$/;
     //     if(regMobile.test(mobile)==false){
     //         mobileId.innerHTML="手机号码不正确，请重新输入";
     //         return false;
     //         }
     //         mobileId.innerHTML="";
     //         return true;
     //     }
     //阅读按钮验证
     function checkcb() {
         var check = false
         if ($('.check').attr('checked')) {

             $('.check').nextAll('span:eq(0)').show()
             check = false;

         } else {
             $('.check').nextAll('span:eq(0)').hide()
             check = true;
         }
         return check;
     }
     function send_user(data) {
        if($(data).next().html()==''){

            username=$(data).val()
            $.get('/register',{'username':username},function (data_2) {
                $(data).next().html(data_2.errors)
            })
            return true
        }
     }
     function last() {
        $.each($('span'),function (index,index2) {
           if(index2.val()!=''){
               return false
           }
           return true
        })
     }

     //提交前静态验证
     function check() {
         var check = checkUser('.username') && checkPwd('.pwd') && checkRepwd('.repwd') && checkcb('.check') && last();
         return check;

     }
 </script>

</head>
<body>
<form action="/register" method="post" onsubmit="return check()">
 <fieldset>
  <legend>
   表单验证小例子
  </legend>
  <h3>
   请输入信息
  </h3>
  <label>
   用户名：
  </label>
  <input type="text" class="username" name="username" onkeyup="checkUser('.username')" onchange="send_user('.username')"/>
  <span ></span>
  <br/>

  <label for="">邮箱:</label>
  <input type="text"  name="email" class="email" onkeyup="checkEmail('.email')" onchange="send_user('.email')">
  <span ></span>
  <br>

  <label>
   密码：
  </label>
  <input type="password" class="pwd" name="password"
         onkeyup="checkPwd('.pwd')" />
  <span ></span>
  <br/>
  <label>
   确认密码：
  </label>
  <input type="password" class="repwd" name="pwdc" onkeyup="checkRepwd('.repwd')"/>
  <span ></span>
  <br/>

  <input type="checkbox" name="checkbox" class="check" onclick="checkcb()"/>
  <label>
   我已经阅读了XX条款并不能同意得更多
  </label>
  <span hidden>清阅读</span>
  <br/>

  <input type="submit" value="走！"/>
 </fieldset>
</form>

</body>
</html>